{{- if eq .Values.inference.framework "triton-vllm" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.inference.serviceName}}
  namespace: {{.Values.inference.serviceNamespace}}
  labels:
    "app.kubernetes.io/component": "{{.Values.inference.serviceName}}"
spec:
  replicas: {{ .Values.inference.modelServer.deployment.replicas }}
  selector:
    matchLabels:
      "app.kubernetes.io/component": "{{.Values.inference.serviceName}}"
  template:
    metadata:
      labels:
        "app.kubernetes.io/component": "{{.Values.inference.serviceName}}"
    spec:
      containers:
        - name: triton-vllm
          image: "{{ .Values.inference.modelServer.image.repository }}:{{ .Values.inference.modelServer.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["tritonserver"]
          args: [
            "--model-repository=/models",
            "--grpc-port=8001",
            "--http-port=8000",
            "--metrics-port=8002",
            "--allow-grpc=true",
            "--allow-http=true",
            "--allow-metrics=true",
            "--log-verbose=1"
          ]
          env:
            {{- if .Values.modelParameters }}
            {{- range $key, $value := .Values.modelParameters }}
            - name: {{ $key | snakecase | upper }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            initialDelaySeconds: 55
            periodSeconds: 5
          resources:
            {{- if eq .Values.inference.accelerator "gpu" }}
            {{- toYaml .Values.inference.modelServer.deployment.resources.gpu | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /models/vllm_model
              name: model-repository
            - mountPath: /dev/shm
              name: dshm
      {{- if .Values.inference.modelServer.deployment.instanceType }}
      nodeSelector:
        beta.kubernetes.io/instance-type: {{ .Values.inference.modelServer.deployment.instanceType }}
      {{- end }}
      {{- if and .Values.inference.modelServer.deployment.topologySpreadConstraints.enabled .Values.inference.modelServer.deployment.topologySpreadConstraints.constraints }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              "app.kubernetes.io/component": "{{$.Values.inference.serviceName}}"
      {{- end }}
      {{- if and .Values.inference.modelServer.deployment.podAffinity.enabled .Values.inference.modelServer.deployment.podAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: topology.kubernetes.io/zone
              labelSelector:
                matchLabels:
                  "app.kubernetes.io/component": "{{$.Values.inference.serviceName}}"
      {{- end }}
      volumes:
        - configMap:
            name: triton-model-repository
            items:
              - key: config.pbtxt
                path: config.pbtxt
              - key: model.json
                path: ./1/model.json
          name: model-repository
        - name: dshm
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.inference.serviceName}}
  namespace: {{.Values.inference.serviceNamespace}}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8002
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    "app.kubernetes.io/component": "{{.Values.inference.serviceName}}"
{{- end }}
